### ISSUE TITLE
Split into 2 packages

### ISSUE THREAD

**Issue by mpadge** [ropenscilabs/pkgcheck#17]
One package to enable local generation of reports, which can be used for general development, the use of which will be a checklist item in submission templates, and another exclusively to serve the plumber endpoints for the review bot to call.

@maelle @noamross The second one will serve responses for both general and statistical review process. Question is: *What should we call that?* More specifically, do we want to give it a name that explicates the direct connection with the responses of our bot? If so, what? Suggestions please!

**Comment by noamross** [comment]
Given that it's mostly internal and won't have a lot of users, I don't think the name is too consquential. `roreport`? `roreviewapi`?

**Comment by maelle** [comment]
I prefer roreviewapi otherwise I can almost guarantee confusions with pkgreport. :wink:

**Comment by mpadge** [comment]
Done now, via [`roreviewapi`](https://github.com/ropenscilabs/roreviewapi) package.
